title: FEA0063
description: Repositório da disciplina de Estruturas de Concreto Armado 1
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Material: www.google.com.br
  Plano de Ensino: https://drive.google.com/open?id=1M1dqHVAgGe07I0-q1JaotlcF2O1f0tCi&usp=drive_fs

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Importante
    color: blue
  new:
    title: Novo
    color: green
  note:
    title: Nota
    color: purple
  warning:
    title: Aviso
    color: red
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Back to top link
back_to_top: true
back_to_top_text: "Voltar ao início"

footer_content: "Copyright &copy; 2023. Construído por Wanderlei Malaquias Pereira Junior e seu grupo de pesquisa.</a>"
