title: PAREpy
description: A starter template for a Jeykll site using the Just the Docs theme!
remote_theme: just-the-docs/just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Release history: https://pypi.org/project/parepy-toolbox/#history

color_scheme: nil

callouts_level: quiet # or loud
callouts:
  highlight:
    title: Highlight
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
  
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy 2023 GPEE.</a>"

logo: "/assets/images/logo-2.png"
favicon_ico: "/assets/images/logo.ico"